# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concediu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=100)),
                ('team_leader_name', models.CharField(max_length=100)),
                ('start_date', models.DateField(max_length=100)),
                ('end_date', models.DateField(max_length=100)),
                ('days_off', models.IntegerField(max_length=100)),
                ('team_leader_email_address', models.EmailField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
