# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170802_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concediu',
            name='days_off',
            field=models.IntegerField(),
        ),
    ]
