# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170802_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='OOHRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=100)),
                ('hours_worked', models.IntegerField()),
                ('from_between', models.DateTimeField()),
                ('motivation', models.CharField(max_length=100)),
                ('team_leader_email', models.CharField(max_length=100)),
            ],
        ),
    ]
