# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_oohrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oohrequest',
            name='from_between',
        ),
        migrations.AddField(
            model_name='oohrequest',
            name='end',
            field=models.CharField(default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oohrequest',
            name='start',
            field=models.CharField(default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oohrequest',
            name='hours_worked',
            field=models.DurationField(),
        ),
    ]
