# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170803_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oohrequest',
            name='team_leader_email',
            field=models.EmailField(max_length=100),
        ),
    ]
