# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170803_1651'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OOHRequest',
        ),
    ]
