# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_oohrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='concediu',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
