# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_concediu_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pontaj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=4)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('CNP', models.CharField(max_length=13)),
                ('team_leader_email', models.EmailField(max_length=100)),
            ],
        ),
    ]
