# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_pontaj'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontaj',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
