# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_concediu_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='OOHRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('day', models.DateField(max_length=100)),
                ('call_time', models.TimeField()),
                ('worked_time', models.IntegerField()),
                ('incident_number', models.CharField(max_length=100)),
                ('team_leader_email', models.EmailField(max_length=100)),
            ],
        ),
    ]
