# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_oohrequest_call_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='oohrequest',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
