# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_oohrequest_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oohrequest',
            name='incident_number',
            field=models.SlugField(max_length=100),
        ),
    ]
