# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20170808_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='concediu',
            name='rejectFlag',
            field=models.BooleanField(default=False),
        ),
    ]
