# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_concediu_rejectflag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('marca', models.IntegerField()),
                ('CNP', models.CharField(max_length=13)),
                ('location', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('team_leader_email', models.EmailField(max_length=100)),
            ],
        ),
    ]
