# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20170810_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oohrequest',
            name='incident_number',
            field=models.CharField(max_length=100),
        ),
    ]
